services:
  mariadb:
    container_name: mariadb
    networks:
      - inception
    volumes:
      - mariadb:/var/lib/mysql
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    env_file:
      - .env
    secrets:
      - db_user
      - db_root_password
      - db_password
    restart: on-failure
    expose:
      - "3306"
  
  nginx:
    container_name: nginx
    networks:
      - inception
    depends_on:
      - wordpress
      - adminer
      - redis
    volumes:
      - ./requirements/bonus/static_site:/usr/share/nginx/html/static_site
      - wordpress:/var/www/wordpress
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: on-failure
    ports:
      - "443:443"
      - "8080:8080"
  
  wordpress:
    container_name: wordpress
    networks:
      - inception
    volumes:
      - wordpress:/var/www/wordpress
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    env_file:
      - .env
    secrets:
      - db_user
      - db_password
      - wp_admin_user
      - wp_admin_password
      - wp_user
      - wp_user_password
    restart: on-failure
    depends_on:
      - mariadb
      - redis
    ports:
      - "8443:443"
    expose:
      - "8443"
  
  redis:
    container_name: redis
    build:
      context: requirements/bonus/redis
      dockerfile: Dockerfile
    volumes:
      - redis:/data
    env_file:
      - .env
    restart: on-failure
    networks:
      - inception
    ports:
      - "6379:6379"
    expose:
      - "6379"

  ftp:
    container_name: ftp
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html
    build:
      context: requirements/bonus/ftp
      dockerfile: Dockerfile
    secrets:
      - ftp_user
      - ftp_password
    restart: on-failure
    ports:
      - "21:21"
    
  static_site:
    container_name: static_site
    networks:
      - inception
    build:
      context: requirements/bonus/static_site
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: on-failure
    ports:
      - "8081:80"

  adminer:
    container_name: adminer
    networks:
      - inception
    build:
      context: requirements/bonus/adminer
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - ADMINER_DEFAULT_SERVER=mariadb
    restart: on-failure
    ports:
      - "8090:8080"

  nginx-exporter:
    container_name: nginx-exporter
    build:
      context: requirements/bonus/nginx-exporter
      dockerfile: Dockerfile
    depends_on:
      - nginx
    restart: on-failure
    networks:
      - inception

  prometheus:
    container_name: prometheus
    build:
      context: requirements/bonus/prometheus
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "9090:9090"
    volumes:
      - prometheus:/prometheus
    networks:
      - inception

  grafana:
    container_name: grafana
    build:
      context: requirements/bonus/grafana
      dockerfile: Dockerfile
    restart: on-failure
    secrets:
      - grafana_admin
      - grafana_password
    volumes:
      - grafana:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - inception

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: '/home/mwallage/data/wordpress'

  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: '/home/mwallage/data/mariadb'

  prometheus:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: '/home/mwallage/data/prometheus'
    
  grafana:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: '/home/mwallage/data/grafana'

  redis:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: '/home/mwallage/data/redis'
    
secrets:
  db_user:
    file: ../secrets/db_user.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_password:
    file: ../secrets/db_password.txt
  wp_admin_user:
    file: ../secrets/wp_admin_user.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt
  wp_user:
    file: ../secrets/wp_user.txt
  wp_user_password:
    file: ../secrets/wp_user_password.txt
  ftp_user:
    file: ../secrets/ftp_user.txt
  ftp_password:
    file: ../secrets/ftp_password.txt
  grafana_admin:
    file: ../secrets/grafana_admin.txt
  grafana_password:
    file: ../secrets/grafana_password.txt

networks:
  inception:
    driver: bridge